version: '3.9'

services:
    skeleton-py-flask-api:
        container_name: skeleton-py-flask-api
        build:
            context: .
            dockerfile: docker/Dockerfile
        env_file:
            - dev.env
        depends_on:
            - skeleton-py-flask-api-postgres
        volumes:
            - "${PWD}:/opt/app"
        ports:
            - "5050:5050"
        networks:
            skeleton-py-flask-net:

    skeleton-py-flask-api-postgres:
        container_name: skeleton-py-flask-postgres
        image: postgres:13.4-alpine
        restart: on-failure
        volumes:
            - skeleton-py-flask-api-postgres-volume:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file:
            - dev.env
        networks:
            skeleton-py-flask-net:

volumes:
    skeleton-py-flask-api-postgres-volume:

networks:
    skeleton-py-flask-net:
        name: skeleton-py-flask-net
