on:
  workflow_dispatch:
  push:
    branches:
      - main
      - devel
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - devel

jobs:
  secrets-gate:
    runs-on: self-hosted
    outputs:
      ok: ${{ steps.check-secrets.outputs.ok }}
    steps:
      - name: check for secrets needed to run SonarQube
        id: check-secrets
        run: |
          if [ ! -z "${{ secrets.SONAR_TOKEN }}" ] && [ ! -z "${{ secrets.SONAR_HOST_URL }}" ]; then
            echo "::set-output name=ok::true"
          fi
          
  sonarqube:
    runs-on: self-hosted
    needs:
        - secrets-gate
    if: ${{ needs.secrets-gate.outputs.ok == 'true' }}
    services:
      postgres-skeleton-db:
        image: postgres
        env:
          POSTGRES_DB: postgres_rv_database
          POSTGRES_USER: rv_user
          POSTGRES_PASSWORD: rv_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2

      - name: Generate coverage
        run: |
          export PATH="/home/admin/.local/bin:$PATH"
          pip install -U pip
          pip install poetry
          poetry install
          coverage run --source='api' --omit='api/tests/*' manage.py test
          coverage report
          coverage xml
        env:
          POETRY_VIRTUALENVS_CREATE: false
          POSTGRES_NAME: localhost
          POSTGRES_DB: postgres_rv_database
          POSTGRES_USER: rv_user
          POSTGRES_PASSWORD: rv_password

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ github.event.repository.name }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
